backend:
  name: github
  repo: 'alecslupu/alecslupu'
  branch: main
  use_graphql: true

media_folder: "source/uploads"
public_folder: "/uploads/"

collections:
  - name: blog
    label: Blog
    folder: "source/blog/posts/"
    extension: ".html.md"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} -- {{year}}-{{month}}-{{day}}"
    format: frontmatter
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Tags", name: "tags", widget: "select", options: [ "releases", "casestudy" ], required: false }