name: "[CI] Deploy"
on:
  push:
    branches:
      - main
env:
  CI: "true"
  RUBY_VERSION: 3.3.4
  NODE_VERSION: 18.17.1

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - uses: actions/cache@v4
        id: app-cache
        with:
          path: ./spec/decidim_dummy_app/
          key: app-${{ github.sha }}
          restore-keys: app-${{ github.sha }}
      - run: npm install
        name: Build JS
        shell: "bash"
      - run: bundle exec middleman build
        name: Build Website
        shell: "bash"
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          local-dir: "./build/"
          server-dir: /
          dangerous-clean-slate: "true"
          server:  ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
